# Generated by Django 3.0.6 on 2020-05-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('finised', models.BooleanField(default=True)),
                ('datetime', models.DateTimeField(blank=True, default=True)),
            ],
        ),
    ]
